import { chromium } from '@playwright/test';
import fs from 'node:fs';
const browser = await chromium.launch({ channel:'msedge', headless:true });
const errors = [];
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>errors.push(e.message));
page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});
const response=await page.goto('http://127.0.0.1:5173');
if(response.status()!==200)throw Error('Page did not load');
await page.waitForSelector('h1');
await page.waitForTimeout(1200);
fs.mkdirSync('.test-artifacts',{recursive:true});
for(const id of ['about','skills','projects','certifications','education','contact']){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.waitForTimeout(700);}
await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(400);
await page.screenshot({path:'.test-artifacts/desktop.png',fullPage:true});
for (const width of [1440,1024,768,760,390,360]) {
 await page.setViewportSize({width,height:900});
 await page.waitForTimeout(150);
 const layout=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,image:document.querySelector('.about-photo img').naturalWidth}));
 if(layout.document>layout.width)throw Error('Horizontal overflow at '+width+': '+layout.document);
 if(!layout.image)throw Error('Photo did not load');
}
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('navigation').getByRole('link',{name:'Projects',exact:true}).click();
await page.waitForTimeout(1200);
if(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded')!=='false')throw Error('Mobile menu did not close');
await page.locator('.project-card').filter({hasText:'Ubuntu Home Server / NAS'}).getByRole('button',{name:'View architecture',exact:true}).click();
await page.getByRole('dialog').waitFor({state:'visible'});
await page.getByRole('heading',{name:'Home Server / NAS',exact:true}).waitFor({state:'visible'});
await page.keyboard.press('Escape');
if(await page.getByRole('dialog').count())throw Error('Dialog did not close on Escape');
if(await page.locator('.hero-actions').getByRole('link',{name:'GitHub',exact:true}).getAttribute('href')!=='https://github.com/Ayubgardi1')throw Error('Wrong GitHub profile');
if(await page.locator('.project-card').filter({hasText:'College Engineering Campus Network'}).getByRole('link',{name:'View project',exact:true}).getAttribute('href')!=='https://github.com/Ayubgardi1/college-of-engineering-campus-network')throw Error('Wrong project URL');
const cvResponse=await page.request.get('http://127.0.0.1:5173/ayub-whsyar-ahmed-cv.pdf');if(!cvResponse.ok()||(await cvResponse.body()).subarray(0,4).toString()!=='%PDF')throw Error('CV not served');
if(await page.locator('.about-photo img').getAttribute('src')!=='/myphoto.jpg')throw Error('Wrong portrait');
if(await page.locator('#contact').getByRole('link',{name:'Get in touch'}).getAttribute('href')!=='mailto:ayubwshyar6@gmail.com')throw Error('Wrong email link');
if(await page.locator('#contact').getByRole('link',{name:'LinkedIn',exact:true}).getAttribute('href')!=='https://www.linkedin.com/in/ayub-wshyar-03407a344/')throw Error('Wrong LinkedIn link');
if(await page.getByRole('link',{name:'Verify Cisco CCNA badge on Credly (opens in a new tab)'}).getAttribute('href')!=='https://www.credly.com/badges/5695c8cc-0845-4d23-bf40-7ebe9d674d3c/public_url')throw Error('Wrong badge URL');
const downloadEvent=page.waitForEvent('download');await page.getByRole('link',{name:'Download CV'}).click();const download=await downloadEvent;if(download.suggestedFilename()!=='Ayub-Whsyar-Ahmed-CV.pdf')throw Error('CV download failed');
await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
await page.waitForTimeout(700);
await page.screenshot({path:'.test-artifacts/mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});
await page.locator('#skills').scrollIntoViewIfNeeded();
await page.waitForTimeout(800);
if(!await page.locator('nav a[href="#skills"]').evaluate(el=>el.classList.contains('active')))throw Error('Active navigation did not update');
await page.locator('.featured').getByRole('button',{name:'View case study',exact:true}).click();
await page.getByRole('dialog').getByRole('heading',{name:'College Engineering Campus Network'}).waitFor({state:'visible'});
await page.keyboard.press('Escape');
if(!await page.locator('.learning-card').textContent().then(t=>t.includes('NOT YET CERTIFIED')))throw Error('RHCSA status unclear');
await page.emulateMedia({reducedMotion:'reduce'});
if(await page.evaluate(()=>getComputedStyle(document.querySelector('.connections .signal')).animationName)!=='none')throw Error('Reduced motion was ignored');
await page.evaluate(()=>window.scrollTo(0,0));
await page.waitForTimeout(400);
await page.keyboard.press('Tab');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: no runtime errors, image loaded, six responsive widths without overflow, mobile navigation, project dialog, Escape dismissal, GitHub profile and project links, CV PDF, portrait, LinkedIn and phone links, CV download, active navigation, reduced motion.');
await browser.close();
